version: '3.8'

services:
  file-storing-service:
    build:
      context: .
      dockerfile: FileStoringService/Dockerfile
    container_name: file-storing-service
    ports:
      - "5059:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - file-storing-data:/app/storage
      - file-storing-db:/app
    networks:
      - antiplagiat-network

  file-analysis-service:
    build:
      context: .
      dockerfile: FileAnalysisService/Dockerfile
    container_name: file-analysis-service
    ports:
      - "5124:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - FileStoringService__BaseUrl=http://file-storing-service:8080/
    volumes:
      - file-analysis-db:/app
    networks:
      - antiplagiat-network
    depends_on:
      - file-storing-service

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: api-gateway
    ports:
      - "5236:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Services__FileStoringBaseUrl=http://file-storing-service:8080/
      - Services__FileAnalysisBaseUrl=http://file-analysis-service:8080/
    networks:
      - antiplagiat-network
    depends_on:
      - file-storing-service
      - file-analysis-service

networks:
  antiplagiat-network:
    driver: bridge

volumes:
  file-storing-data:
  file-storing-db:
  file-analysis-db: